//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HapticScripter
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealTouchEvent
    {
        public int Duration { get; set; }
        public int Start { get; set; }
        public int Magnitude { get; set; }
        public int Id { get; set; }
    }
}
